apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: "{{ $.Chart.Name }}-redirect-root"
    namespace: {{ .Values.namespace }}
spec:
    redirectRegex:
        regex: "^/$"
        replacement: "/api"
        permanent: true